# Generated by Django 5.0.2 on 2024-03-03 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceitem'),
        ('training', '0006_delete_participanttraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointraining',
            name='serviceitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem', verbose_name='Элемент услуги'),
        ),
        migrations.AddField(
            model_name='jointraining',
            name='type',
            field=models.CharField(choices=[('personal', 'Персональная тренировка'), ('group', 'Групповая тренировка')], default=1, max_length=255, verbose_name='Тип занятия'),
            preserve_default=False,
        ),
    ]
