# Generated by Django 5.0.2 on 2024-03-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceitem'),
        ('training', '0007_jointraining_serviceitem_jointraining_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointraining',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.schedule', verbose_name='Расписание'),
        ),
    ]
