# Generated by Django 5.0.2 on 2024-03-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_userjointraining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userjointraining',
            name='serviceitem',
        ),
    ]
