# Generated by Django 5.0.2 on 2024-03-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_userschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.service', verbose_name='Услуга'),
        ),
    ]
