# Generated by Django 5.0.2 on 2024-03-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_serviceitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='serviceitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
