# Generated by Django 5.0.2 on 2024-03-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_schedule_serviceitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['name'], 'verbose_name': 'Элемент услуги', 'verbose_name_plural': 'Элементы услуги'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='serviceitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem', verbose_name='Услуга элемент'),
        ),
    ]
