# Generated by Django 5.0.2 on 2024-03-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_serviceitem_options_alter_schedule_serviceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='serviceitem',
            new_name='service_item',
        ),
    ]
