# Generated by Django 5.0.2 on 2024-03-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_serviceitem_schedule_service_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='participants',
            field=models.IntegerField(default=10),
        ),
    ]
