# Generated by Django 5.0.2 on 2024-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_activate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата активации'),
        ),
    ]
