# Generated by Django 5.0.1 on 2024-02-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_data_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_type',
        ),
    ]
