# Generated by Django 5.0.1 on 2024-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_username_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
