# Generated by Django 5.0.1 on 2024-02-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_user',
            field=models.BooleanField(default=False, verbose_name='Статус активации'),
        ),
    ]
